### ISSUE TITLE
서비스 관리자 예외처리

### ISSUE THREAD

**Issue by 2oo1s** [WooRibound/WooRibound-API#112]
## 🐛 버그 설명
>어떤 버그인지 간략하게 설명해주세요!

서비스 관리자 기능에서 빼먹은 예외처리 추가

## 🔍 Todo
> 수정할 사항항에 대해 적어주세요!

- [x] 존재하지 않는 사용자의 이력서를 조회하려고 하는 경우
- [x] 존재하지 않는 채용공고를 조회하려고 하는 경우
- [x] 존재하지 않는 지혜를 조회하려고 하는 경우

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
