### ISSUE TITLE
개인 회원 교육 관련 기능 구현

### ISSUE THREAD

**Issue by 2oo1s** [WooRibound/WooRibound-API#22]
## 🛠️ 작업 설명
> 개인 회원 교육 목록 조회 및 교육 신청 기능 개발

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [ ] 교육 목록 조회
- [ ] 교육 상세 조회
- [ ] 지원한 교육 조회
- [ ] 교육 신청

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
