### ISSUE TITLE
KnowHow entity 스키마에 맞게 구현

### ISSUE THREAD

**Issue by 2oo1s** [WooRibound/WooRibound-API#27]
## 🛠️ 작업 설명
>어떤 작업인지 간략하게 설명해주세요!

KnowHow entity 스키마에 맞게 구현

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] 교육과정 관련 파일 삭제
- [x] Knowhow 엔티티 기본 틀 (컬럼, pk, 자료형) 작성
- [x] 엔티티 구체화 (제약조건, 조인컬럼)

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
