### ISSUE TITLE
기업회원 관련 기능 구현

### ISSUE THREAD

**Issue by haewoni** [WooRibound/WooRibound-API#34]
## 🛠️ 작업 설명
> 기업회원 도메인 관련 기능 구현

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [x] 정보 조회
- [x] 정보 수정
- [ ] 공고 등록
- [ ] 공고  조회
- [ ] 공고 지원자 조회
- [ ] 공고 지원자 이력서 조회
- [ ] 고용 직원 목록
- [ ] 고용 직원 평가

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
