### ISSUE TITLE
Entity db 스키마에 맞게 구현

### ISSUE THREAD

**Issue by leesj000603** [WooRibound/WooRibound-API#4]
## 🛠️ 작업 설명
> Entity db 스키마에 맞게 구현

## 🔍 Todo
> 개발할 기능에 대해 적어주세요!

- [ ] 엔티티가 들어갈 패키지 구조 정의
- [ ] 엔티티 기본 틀 (컬럼, pk, 자료형) 작성
- [ ] 엔티티 구체화 (제약조건, 조인컬럼) 

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
- 
-
