### ISSUE TITLE
서비스 관리자 API 프론트 연동

### ISSUE THREAD

**Issue by 2oo1s** [WooRibound/WooRibound-API#77]
## 🐛 버그 설명
>어떤 버그인지 간략하게 설명해주세요!

서비스 관리자 API를 프론트와 연동 시, 발생하는 에러 수정

## 🔍 Todo
> 수정할 사항항에 대해 적어주세요!

- [x] 개인회원 관리 API 수정
- [x] 기업회원 관리 API 수정
- [x] 채용공고 관리 API 수정
- [x] 지혜 관리 API 수정

## 📃 참고한 출처
> 어느 출처를 참고했는지 작성해주세요!
